import { IArticle } from '../interfaces';

const userNews: Array<IArticle> = [
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:24Z',
    id: '1',
    title: '1olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:25Z',
    id: '2',
    title: '2olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:26Z',
    id: '3',
    title: '3olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:27Z',
    id: '4',
    title: '4olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:28Z',
    id: '5',
    title: '5olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:29Z',
    id: '6',
    title: '6olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:30Z',
    id: '7',
    title: '7olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:35Z',
    id: '8',
    title: '8olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:40Z',
    id: '9',
    title: '9olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:45Z',
    id: '10',
    title: '10olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
  {
    author: 'Lily Nothling',
    content: 'osted February 15, 2019 07:50:15 An Australian Army soldier has been charged with raping a 16-year-old girl at the Gallipoli Barracks at Enoggera in Brisbane. Police alleged the girl was smuggled past security in the boot of a car on January 14. The A',
    description: 'The 24-year-old soldier is accused of raping the 16-year-old who police say was smuggled past security at Brisbanes Gallipoli Barracks in the boot of a car.',
    publishedAt: '2019-02-14T20:50:55Z',
    id: '11',
    title: '11olider charged over alleged rape of 16yo in army',
    urlToImage: 'https://www.abc.net.au/news/image/2250770-16x9-700x394.jpg',
    url: "https://apnews.com/7aa798a8d0f5420a84dfcbc23a09c401",
    isUserNews: true,
  },
];

export default userNews;
